# -------------------------------------------------------------------------------------
# Author Configuration
# -------------------------------------------------------------------------------------

name = "家园工程"
email = "homeporject7@gmail.com"
link = "https://github.com/homepoject7"
