# -------------------------------------------------------------------------------------
# Author Configuration
# -------------------------------------------------------------------------------------

name = "家园工程"
email = "homeporject7d@gmail.com"
link = "https://github.com/homeproject7"

avatar = "/images/avatar.png"
