name: Update Post
on:
  push:
    branches: [ content ]
    paths:
      - 'assets/**'
      - 'config/**'
      - 'content/**'
      - 'data/**'
      - 'static/**'
      - 'themes/**'
jobs:
  Actions-Hugo-Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: latest
          extended: true

      - name: Build
        run: hugo -v --gc --minify

      - name: Deploy to Github Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          # See https://github.com/JamesIves/github-pages-deploy-action#configuration-
          repository-name: homeproject7/homeproject7.github.io
          branch: main
          token: ${{ secrets.ACCESS_TOKEN }}
          folder: public
          clean: true
          single-commit: true
